In [135]:
import torch
import torch.nn as nn
from torch.nn import functional as F
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [136]:
%%time
start_time = time.time()
# matrix operations here
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00000000
CPU times: total: 0 ns
Wall time: 0 ns


In [137]:

torch_randl = torch.rand(100, 100, 100, 100).to(device)  
torch_rand2 = torch.rand(100, 100, 100, 100).to(device) 
np_rand1 = torch.rand(100, 100, 100, 100) 
np_rand2 = torch.rand(100, 100, 100, 100) 

start_time = time.time()
 
rand = (torch_randl @ torch_rand2) 

end_time = time.time() 

elapsed_time = end_time - start_time 
print(f"{elapsed_time:.8f}") 

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2) 
end_time = time.time() 
elapsed_time = end_time - start_time 
print(f"{elapsed_time:.8f}") 

0.03121567
0.15743113


In [138]:
#torch.stack, torch.multinominal, torch.tril, torch.triu, input.T/ input.transpose, nn.Linear, torch.cat, F.softmax (show all the posibilites)

#Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
#10% or 0.1=>0,90% or 0.9 =>1 each probability points to the index of the probability in the tensor.
#Draw 5 samples from the multi dimensinal distribution.
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [139]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [140]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [141]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [142]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [143]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [144]:
input = torch.zeros(2, 3, 4)
out1 = input.transpose(0, 1)
out2 = input.transpose(-2,-1)
print(out1.shape)
print(out2.shape)
# torch.permute works the same but you provide the new order of dimens

torch.Size([3, 2, 4])
torch.Size([2, 4, 3])


In [145]:
tensor1 = torch.tensor([1, 2, 1]) 
tensor2 = torch.tensor([4, 5, 6]) 
tensor3 = torch.tensor([7, 8, 9]) 

# Stock the tensors aLong a new dimension 
stacked_tensor = torch.stack([tensor1, tensor2, tensor3]) 
stacked_tensor 

tensor([[1, 2, 1],
        [4, 5, 6],
        [7, 8, 9]])

In [146]:
import torch.nn as nn 
sample = torch.tensor([10.,10.,10.]) 
linear = nn.Linear(3, 3, bias=False) 
print(linear(sample))

tensor([8.7592, 3.7868, 2.1959], grad_fn=<SqueezeBackward4>)


In [147]:
import torch.nn.functional as F

#create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

#applay softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [148]:
#inicilizate an embeding layer
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

#create some input index
input_indices = torch.LongTensor([1, 5, 3, 2])

#Applay the embedding layer
embedded_output = embedding(input_indices)
#The output will be a tensor of shape (4, 100), where 4 is the number of inputs
#and 100 is the dimensionality of the embeeeding vector.
print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 6])
tensor([[ 0.0105, -0.5040,  0.3362,  0.2380, -0.3242,  0.8310],
        [-0.3396, -0.3755, -0.3352, -0.9580,  2.1080,  0.1654],
        [-1.2255, -1.7282, -0.0298,  0.0708, -1.8721, -0.9729],
        [ 0.5998, -1.5200,  1.1445,  1.6164,  0.1353,  0.9846]],
       grad_fn=<EmbeddingBackward0>)


In [149]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
#print(a @ b)
print(torch.matmul(a, b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [150]:
int_64 = torch.randint(1, (3, 2)).float()
#type int64
float_32 = torch.rand(2,3)
#type float32
result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [151]:
a = torch.rand(2, 3, 5)
print(a.shape)
x, y, z = a.shape
a = a.view(x,y,z)
# print(x, y, z)
print(a.shape)

torch.Size([2, 3, 5])
torch.Size([2, 3, 5])


In [152]:
input = torch.rand((4, 8, 10))
B, T, C = input.shape
output = input.view(B*T, C)
print(output)
#print(input)
print(output[:, -1, :])

tensor([[0.8949, 0.1138, 0.9575, 0.5012, 0.9831, 0.8875, 0.8429, 0.1148, 0.7733,
         0.2116],
        [0.2554, 0.4390, 0.1937, 0.0547, 0.3755, 0.9390, 0.3219, 0.1232, 0.7577,
         0.0277],
        [0.6526, 0.8862, 0.0325, 0.9502, 0.8744, 0.8876, 0.7200, 0.6586, 0.2728,
         0.8926],
        [0.5057, 0.6314, 0.4774, 0.6893, 0.9179, 0.3054, 0.8743, 0.0777, 0.6961,
         0.3107],
        [0.1471, 0.6143, 0.8642, 0.8503, 0.1445, 0.1865, 0.9823, 0.4319, 0.6373,
         0.2004],
        [0.3171, 0.2936, 0.8939, 0.4059, 0.6949, 0.2772, 0.9702, 0.2568, 0.4470,
         0.9541],
        [0.3498, 0.6457, 0.8724, 0.8611, 0.0340, 0.2716, 0.9393, 0.5874, 0.4750,
         0.1312],
        [0.8390, 0.3796, 0.0512, 0.1406, 0.8153, 0.7409, 0.0154, 0.9494, 0.9887,
         0.9459],
        [0.2505, 0.4423, 0.5256, 0.3267, 0.0077, 0.6233, 0.1826, 0.7095, 0.5826,
         0.5177],
        [0.9413, 0.6166, 0.0314, 0.1921, 0.2290, 0.7011, 0.7875, 0.7339, 0.8504,
         0.9725],
        [0

IndexError: too many indices for tensor of dimension 2

In [158]:
x = torch.tensor([10], dtype=torch.float32)
y = F.tanh(x)
print(y)

tensor([1.])
